---
- name: Installer Apache avec conditions
  hosts: all
  become: true
  tasks:
    - name: Installer Apache uniquement sur Debian/Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Afficher message de confirmation
      debug:
        msg: "Apache a été installé avec succès sur {{ ansible_facts['hostname'] }}"
      when: ansible_facts['os_family'] == "Debian"
