---
- name: Copier un fichier vers machines clientes
  hosts: all
  tasks:
    - name: Copie du fichier sdv.conf vers /tmp
      ansible.builtin.copy:
        src: /root/sdv.conf
        dest: /tmp/sdv.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
