---
- name: Créer un fichier dynamiquement
  hosts: all
  vars:
    nom_fichier: toto
  tasks:
    - name: Créer un fichier vide avec nom dynamique
      ansible.builtin.file:
        path: "/tmp/{{ nom_fichier }}.log"
        state: touch
        owner: root
        group: root
        mode: "0644"
